### ISSUE TITLE
After update broken

### ISSUE THREAD

**Issue by disquette38** [jprochazka/adsb-receiver#202]
Hello,
after update my feeder is down !
reboot but write 
ADS-B Receiver Portal Updated
Your portal has been upgraded to v2.0.3.
not map not system

**Comment by radiostationx** [comment]
The station should still be feeding data to external sites.
You need to delete a file and run /install again.
For details please see closed issue #185

**Comment by radiostationx** [comment]
The station should still be feeding data to external sites.
You need to delete a file and run /install again.
For details please see closed issue #185
When you follow the steps in #185,the map and other tabs should be working again.

**Comment by radiostationx** [comment]
See post /instructions to user haran below 

http://discussions.flightaware.com/ads-b-flight-tracking-f21/ads-b-receiver-project-setup-scripts-t36532-1125.html

**Comment by jprochazka** [comment]
I need a little more information in order to help.

Could you elaborate on any errors you may see?
Is the map in question the dump1090 map?
What version did you upgrade from?

If you got the message "Your portal has been upgraded to v2.0.3" the upgrade went fine. Actually the only thing "upgraded" by upgrading from v2.0.2 to v2.0.3 is the version number. The rest would have been taken care of when running install.sh.

**Comment by jprochazka** [comment]
I found a missed version variable which more than likely is the source of the problem.
Overwrite the file /var/www/html/classes/template.class.php with the contents of the fixed file found at https://raw.githubusercontent.com/jprochazka/adsb-receiver/master/build/portal/html/classes/template.class.php or use the upgrade instructions found in the readme file.

**Comment by disquette38** [comment]
After applying the patch, I still have the probleme.always the message "upgrade ok" the time zone change is not taken into account, (still on Africa / Abidjan) click on reference portal on upgrade OK
but the map is ok http:192.168..../dump1090/gmap.html

**Comment by disquette38** [comment]
after new install from image error

/home/pi/adsb-receiver/bash/portal/install.sh: line 471: addr: command not found
PORTAL SETUP IS NOT YET COMPLETE
In order to complete the portal setup process visit the following URL in your favorite web browser.
http:///install/

Enter the requested information and submit the form to complete the portal setup.
It is recomended that after setting up the portal you delete the install directory.

Press enter to continue...

**Comment by jprochazka** [comment]
Is this a Lite install?

If so did you install this required patch?
https://www.adsbreceiver.net/2016/04/27/patch-v2-0-0-2016-04-28-1-available/

If not or are unsure check the file /var/www/html/data/settings.xml and make sure the following settings reside within this file:

    <setting>
        <name>timeZonee</setting>
        <value/>
    </setting>
    <setting>
        <name>version</setting>
        <value/>2.0.3</version>
    </setting>
    <setting>
        <name>patch</name>
        <version/>
    <setting>

**Comment by jprochazka** [comment]
This issue should be resolved once the web based installation step is removed.

**Comment by jprochazka** [comment]
Issue had to do with settings.xml being overwritten when upgrading the portal. The fix is now present in the master branch and will be included in the upcoming 2.1.0 release.
