### ISSUE TITLE
2 . 6 . 2 fail

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-receiver#409]
The ADS-B Receiver Project Preliminary Setup Process

  Checking to make sure the whiptail and git packages are installed...
  ------------------------------------------------------------------------------

  Checking if the package whiptail is installed... [OK]
  Checking if the package git is installed... [OK]

  ------------------------------------------------------------------------------
  The whiptail and git packages are installed.

Press enter to continue...
  Detecting CPU architecture...

   The ADS-B Receiver Project v2.6.1 Installer

  Setting up dump1090-mutability...

  ------------------------------------------------------------------------------

  Installing packages needed to fulfill dependencies for dump1090-mutability...

  Checking if the package git is installed... [OK]
  Checking if the package curl is installed... [OK]
  Checking if the package build-essential is installed... [OK]
  Checking if the package debhelper is installed... [OK]
  Checking if the package cron is installed... [OK]
  Checking if the package librtlsdr-dev is installed... [OK]
  Checking if the package libusb-1.0-0-dev is installed... [OK]
  Checking if the package rtl-sdr is installed... [OK]
  Checking if the package pkg-config is installed... [OK]
  Checking if the package lighttpd is installed... [OK]
  Checking if the package fakeroot is installed... [OK]

  Begining the dump1090-mutability installation process...

  Installing blacklist to prevent unwanted kernel modules from being loaded...  Entering the dump1090-mutability git repository directory...
  Updating the local dump1090-mutability git repository...

error: cannot open .git/FETCH_HEAD: Permission denied

  Building and installing the dump1090-mutability package...

  Building the dump1090-mutability package...

dpkg-buildpackage: info: source package dump1090-mutability
dpkg-buildpackage: info: source version 1.15~dev
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Oliver Jowett <oliver@mutability.co.uk>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build dump1090
 fakeroot debian/rules clean
dh clean
dh: Compatibility levels before 9 are deprecated (level 8 in use)
   dh_testdir
   dh_auto_clean
dh_auto_clean: Compatibility levels before 9 are deprecated (level 8 in use)
        make -j1 clean
make[1]: Entering directory '/home/pi/adsb-receiver/build/dump1090-mutability/dump1090'
rm -f *.o compat/clock_gettime/*.o compat/clock_nanosleep/*.o dump1090 view1090 faup1090 cprtests crctests
rm: cannot remove 'anet.o': Permission denied
rm: cannot remove 'convert.o': Permission denied
rm: cannot remove 'cpr.o': Permission denied
rm: cannot remove 'cprtests.o': Permission denied
rm: cannot remove 'crc.o': Permission denied
rm: cannot remove 'demod_2400.o': Permission denied
rm: cannot remove 'dump1090.o': Permission denied
rm: cannot remove 'icao_filter.o': Permission denied
rm: cannot remove 'interactive.o': Permission denied
rm: cannot remove 'mode_ac.o': Permission denied
rm: cannot remove 'mode_s.o': Permission denied
rm: cannot remove 'net_io.o': Permission denied
rm: cannot remove 'stats.o': Permission denied
rm: cannot remove 'track.o': Permission denied
rm: cannot remove 'util.o': Permission denied
rm: cannot remove 'view1090.o': Permission denied
rm: cannot remove 'dump1090': Permission denied
rm: cannot remove 'view1090': Permission denied
rm: cannot remove 'cprtests': Permission denied
Makefile:63: recipe for target 'clean' failed
make[1]: *** [clean] Error 1
make[1]: Leaving directory '/home/pi/adsb-receiver/build/dump1090-mutability/dump1090'
dh_auto_clean: make -j1 clean returned exit code 2
debian/rules:30: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2

  Installing the dump1090-mutability package...

(Reading database ... 43011 files and directories currently installed.)
Preparing to unpack .../dump1090-mutability_1.15~dev_armhf.deb ...
Unpacking dump1090-mutability (1.15~dev) over (1.15~dev) ...
Setting up dump1090-mutability (1.15~dev) ...
/var/lib/dpkg/info/dump1090-mutability.config: 1: /etc/default/dump1090-mutability: gain: not found
dpkg: error processing package dump1090-mutability (--install):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for systemd (232-25+deb9u2) ...
Errors were encountered while processing:
 dump1090-mutability

  Checking that the dump1090-mutability package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "-mutability" could not be installed.

  ------------------------------------------------------------------------------
  Dump1090-mutability setup halted.

Press enter to continue...

Using an instal/ sh option.  Updated OS, ok. Chose to update 1.1.5, MLAT (always says there is a new version and portal.  Got to the 1 1 5 update, above error.  Tried again, not updating OS and only updating 1 1 5. same error

**Comment by orionjb2001** [comment]
Well my old image is now dead.  Will wait to see if you can fix before re imaging, which I don't really want to do.  Glad I tried the PI3 B that is 12" away from me and not the one up the pole :)

**Comment by radiostationx** [comment]
Strange, I Installed the latest 2.6.2. mutability image yesterday on pi2 test rig , OS updated fine (hardly any updates done as Joe must have built this in the last few days), Mutability and portal installed, no issues found as yet.

**Comment by orionjb2001** [comment]
When you say installed, new image or upgrade to present image??

**Comment by radiostationx** [comment]
orionjb2001 ,New image downloaded 7th, installed 7th.

**Comment by orionjb2001** [comment]
Nothing strange in your result, obviously the new image is fine, the updating of a current image is my/the problem. ☺

**Comment by orionjb2001** [comment]
tried again this morning, same result :(

**Comment by orionjb2001** [comment]
Well just because it looks like I am going to have to re image :( I thought I would try a new install method, as per the quick install instructions, same result. :( Re imaging now, AGAIN,  because something is again broken  :(

**Comment by orionjb2001** [comment]
Ok.,as Radiostationx eluded earlier, the new image, downloaded etc, works.  Some comments, even though selecting no configuration for Postfix, the script still after that, goes through something that shows the Postfix name (not a programmer)??  Otherwise all appears ok.  Have some more coloured rings, been added??  Now a feature requset, can the FA piaware setup have an option to re enter your station unique id numbers, saving you afterwards, from executing the scripts to load your  unique station ID onto your new card??? (I will add that to feature request).

**Comment by orionjb2001** [comment]
So............ the problem remains, you can not update your current card, using install.sh, for sure.  I also believe if someone was going to install by downloading files, instead of installing an image, it will not work either??

**Comment by jprochazka** [comment]
I would say not a 2.6.2 fail but a permissions issue...
```
Updating the local dump1090-mutability git repository...

error: cannot open .git/FETCH_HEAD: Permission denied
```
First question would be at some point did you clone the repository as a sudo user at some time outside using the scripts? Either way delete the directory ~/adsb-receiver/build/dump1090-mutability and rerun the script it should solve the problem.

**Comment by orionjb2001** [comment]
I tired deleting that directory, but it did not fix it with the next .install/sh.  I can't recall cloning outside but also doesn't mean that I did...  Anyway, wanted to put a new class 3 SD card in the PI3B+ so up on the roof, re-imaged with new card, some ABCD2345 tweaks with replacing the two clocks map with the 1090  FA map and all running very sweetly.  No problems with having to image card, update on old PI3B, then running in the 3B+, so that update perfect, thanks.   :)
